/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   parse_players.c                                    :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: mnunnari <marvin@42.fr>                    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2017/09/28 23:37:04 by mnunnari          #+#    #+#             */
/*   Updated: 2017/09/29 21:08:26 by mnunnari         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "corewar_vm.h"

/*
** check if the player number isnt already assigned
*/

int			is_unique(int player_nbr, t_vm *vm)
{
	int		i;

	i = 0;
	while (i < vm->players_nbr)
	{
		if (vm->players[i].number == player_nbr)
			return (0);
		i++;
	}
	return (1);
}

/*
** parse player number given after the option -n
*/

int			parse_player_nbr(char **argv, int *i, t_vm *vm)
{
	int			player_nbr;

	*i += 1;
	if (!argv[*i])
		print_usage();
	if (!ft_isint(argv[*i]))
		ft_err(1, "Error: option -n must be followed by an integer");
	player_nbr = ft_atoi(argv[*i]);
	*i += 1;
	if (!is_unique(player_nbr, vm))
		ft_err(1, "Error: player number %d already used (maybe automatically)", player_nbr);
	return (player_nbr);
}

/*
** generate players numbers
*/

int			get_next_nbr(t_vm *vm)
{
	static int		nbr;

	nbr++;
	while (!is_unique(nbr, vm))
		nbr++;
	return (nbr);
}

/*
** parse all the players.
** if the users dont pass a number it is generated by the function
** get_next_nbr
*/

void		parse_players(char **argv, int *i, t_vm *vm)
{
	t_player	player;
	int			player_nbr;

	vm->players_nbr = 0;
	while (argv[*i])
	{
		if (ft_strequ(argv[*i], "-n"))
			player_nbr = parse_player_nbr(argv, i, vm);
		else
			player_nbr = get_next_nbr(vm);
		if (!argv[*i])
			print_usage();
		player = parse_player(argv[*i]);
		player.number = player_nbr;
		vm->players[vm->players_nbr] = player;
		vm->last_alive = -player.number;
		vm->players_nbr++;
		if (vm->players_nbr > MAX_PLAYERS)
			ft_err(1, "Error: Too many players");
		*i += 1;
	}
}
